services:
  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - 5000:8080
      - 50000:50000
    container_name: jenkins
    volumes:
      - ./pipeline1/jenkins_configuration:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock